version: "3.8"

services:
  server:
    build: ./server
    restart: on-failure
    depends_on:
      - pg
    env_file:
      - ./server/.env.local
    ports:
      - "42069:42069"
  messages-indexer:
    build: ./messages-indexer
    restart: on-failure
    depends_on:
      - pg
      - server
    env_file:
      - ./messages-indexer/.env
  pg:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres-data:
