version: "3.8"

services:
  ponder:
    build: ./ponder
    restart: on-failure
    depends_on:
      - pg
    ports:
      - "42059:42069"
    volumes:
      - ./ponder/.ponder:/app/.ponder
    environment:
      - PONDER_RPC_URL_ETHEREUM=${PONDER_RPC_URL_ETHEREUM}
      - PONDER_RPC_URL_SEPOLIA=${PONDER_RPC_URL_SEPOLIA}
      - PONDER_RPC_URL_ARBITRUM=${PONDER_RPC_URL_ARBITRUM}
      - PONDER_RPC_URL_ARBITRUM_SEPOLIA=${PONDER_RPC_URL_ARBITRUM_SEPOLIA}
      - PONDER_RPC_URL_POLYGON=${PONDER_RPC_URL_POLYGON}
      - PONDER_RPC_URL_BLAST=${PONDER_RPC_URL_BLAST}
      - PONDER_RPC_URL_TAIKO_KATLA=${PONDER_RPC_URL_TAIKO_KATLA}
      - PONDER_RPC_URL_TRON_SHASTA=${PONDER_RPC_URL_TRON_SHASTA}
      - PONDER_RPC_URL_DARWINIA=${PONDER_RPC_URL_DARWINIA}
      - PONDER_RPC_URL_CRAB=${PONDER_RPC_URL_CRAB}
      - PONDER_RPC_URL_PANGOLIN=${PONDER_RPC_URL_PANGOLIN}
      - PONDER_RPC_URL_PANGORO=${PONDER_RPC_URL_PANGORO}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}
      - PANGORO_MAX_REQUESTS_PER_SECOND=${PANGORO_MAX_REQUESTS_PER_SECOND}

  scanner:
    build: ./scanner
    restart: on-failure
    depends_on:
      - pg
      - ponder
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pg:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
