name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  publish-docker-image:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v1.2

      - name: Build ponder with sha
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ponder
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:staging

      - name: Build ponder with tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: ponder
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:${{ env.GIT_TAG_NAME }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:latest

      - name: Build server with sha
        uses: docker/build-push-action@v3
        with:
          push: true
          context: api
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/server:sha-${{ env.SHA }
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/server:staging

      - name: Build server with tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: api
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/server:${{ env.GIT_TAG_NAME }
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/server:latest

